// <auto-generated />
namespace KarolCamp.Repositorio.EF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class bancoinicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bancoinicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201310010017377_banco inicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
