// <auto-generated />
namespace KarolCamp.Repositorio.EF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class criadooarquivo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criadooarquivo));
        
        string IMigrationMetadata.Id
        {
            get { return "201310010120047_criado o arquivo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
